---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
    - name: Install nginx
      yum: name={{item}} state=installed
      with_items:
        - nginx
        - wget
        - curl

