---
- hosts: server2.abc.com
  become: yes
  remote_user: test
  vars:
   server_ip: 192.168.0.10
  tasks:
   - name: Install nginx
     yum: name=nginx state=installed
   - name: copy nginx file
     template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
   - name: start the service
     service: name=nginx state=started
