---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
    - name: Install nginx
      yum: name=nginx state=installed
      tags: install
    - name: copy index.html
      copy: src=index.html dest=/usr/share/nginx/html
      tags: copy
    - name: start the service
      service: name=nginx state=started
      tags: always

