---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
    - name: create a tomcat directory
      file: path=/opt/tomcat state=directory
    - name: Download tomcat
      get_url: 
         url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.86/bin/apache-tomcat-8.5.86.tar.gz
         dest: /opt/tomcat 
    - name: unarchive tomcat file
      unarchive:
         src: /opt/tomcat/apache-tomcat-8.5.86.tar.gz
         dest: /opt/tomcat
         copy: no
    - name: start tomcat
      shell: nohup  /opt/tomcat/apache-tomcat-8.5.86/bin/catalina.sh start

