---
- hosts: server2.abc.com
  remote_user: test
  become: yes
  tasks:
    - name: Install nginx
      yum: name=nginx state=installed
      when: ansible_os_family == "Debian"
    - name: Install httpd 
      yum: name=httpd state=installed
      when: ansible_os_family == "RedHat"
    - name: copy index.html
      copy: src=index.html dest=/usr/share/nginx/html
    - name: start the service
      service: name=nginx state=started

